### ISSUE TITLE
Implement a Rate Limiter

### ISSUE THREAD

**Issue by RobWin** [RobWin/javaslang-circuitbreaker#12]
Rate limiters are used to restrict the rate at which a backend is allowed to be accessed.

**Comment by storozhukBM** [comment]
Didn't notice this issue. So repost my question here.
I've already look through [this](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/RateLimiter.java) and several other implementations. And have overall understanding of pros and cons of different algorithms. But I don't sure that such feature should be added to javaslang-circuitbreaker because it is already concise and beautiful single responsibility library. 
On my current project I've created abstraction called `Gateway`. Every API call is proxied through this `Gateway` and it is responsible for invocation of circuitBreaker, requestLimit and/or metrics.

Like that:
```java
public class GatewayInterceptor implements MethodInterceptor {
    private final Logger log = LoggerFactory.getLogger(GatewayInterceptor.class);
    private final ApiType apiType;
    private final Try.CheckedFunction<MethodInvocation, Object> gatewayInvoke;

    public GatewayInterceptor(ApiType apiType, RequestLimit requestLimit, CircuitBreaker circuitBreaker) {
        this.apiType = apiType;
        Try.CheckedFunction<MethodInvocation, Object> circuitBreakerInvoke = CircuitBreaker.decorateCheckedFunction(
            MethodInvocation::proceed,
            circuitBreaker
        );
        Try.CheckedFunction<MethodInvocation, Object> requestLimitInvoke = RequestLimit.decorateCheckedFunction(
            circuitBreakerInvoke,
            requestLimit
        );
        gatewayInvoke = requestLimitInvoke;
    }

    @Override public Object invoke(final MethodInvocation invocation) throws Throwable {
        Object result = Try.success(invocation)
            .mapTry(gatewayInvoke)
            .onFailure(throwable -> log.error("Error in invocation of {} API: {}", apiType, throwable.getMessage()))
            .get();
        return result;
    }
}
```
@tomfitzhenry What do you think about it? Should we enhance javaslang-circuitbreaker or create additional library that will compose  few other libraries?

**Comment by RobWin** [comment]
@tomfitzhenry is not the maintainer, but it's me :)

If a RateLimiter implementation is lightweight in the sense that we don't need any other 3rd party libraries, we can add it to javaslang-circuitbreaker. A RateLimiter is also some sort of CircuitBreaker. A RateLimiter can forbid further calls, if a rate limit has exceeded.

The retry functionality is also not 100% related to CircuitBreakers.

**Comment by storozhukBM** [comment]
@RobWin OK. I've got it. It'd be a pleasure to make a contribution to your project. I'll make a fork and create a pull request.

**Comment by RobWin** [comment]
@storozhukBM That's great. Just put your code into a package called `ratelimiter`.

**Comment by RobWin** [comment]
@storozhukBM If you like, you can join our Gitter channel: https://gitter.im/javaslang/javaslang-circuitbreaker
